version: 2.1

jobs:
  getdeps:
    docker:
      - image: "cimg/elixir:1.13.3"
    steps:
      - checkout
      - restore_cache:
          key: v2-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
      - run: mix local.hex --force
      - run: mix deps.get
      - save_cache:
          key: v2-mix-cache-{{ .Branch }}-{{ checksum "mix.lock" }}
          paths: "deps"
      - persist_to_workspace:
          paths:
          - project
          - .mix
          - .hex
          root: ~/
  build:
    docker:
      - image: "cimg/elixir:1.13.3"
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: mix compile
  test:
    docker:
      - image: "cimg/elixir:1.13.3"
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: mix test
  credo:
    docker:
      - image: "cimg/elixir:1.13.3"
    steps:
      - checkout
      - attach_workspace:
          at: ~/
      - run: mix credo

workflows:
  build_and_test:
    jobs:
      - getdeps
      - credo:
          requires:
            - getdeps
      - build:
          requires:
            - getdeps
      - test:
          requires:
            - getdeps
