version: 2.1

jobs:
  build:
    docker:
      - image: "cimg/elixir:1.13.3"
    steps:
      - checkout
      - run: elixir ./lib/tic_tac_toe.ex
  test:
    docker:
      - image: "cimg/elixir:1.13.3"
    steps:
      - checkout
      - run: mix test

workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
